// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzhmzqquperadflcfxmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6aG16cXF1cGVyYWRmbGNmeG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTI4MzUsImV4cCI6MjA2MjE2ODgzNX0.mBF5JcWhnFL40-DWgp-KFnm4GjoVwkQSBFwPeBOaayE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);